version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: register_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo_db:27017/register_app
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
